title: Hi, I am  Rhea Bhalekar
description: A Robotics Engineer 
theme: jekyll-theme-cayman
navbar:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Publications"
    url: /publications
  - title: "Contact"
    url: /contact
